title: Machine Learning 2025-ii
description: Universidad de La Sabana
sitename: Machine Learning
baseurl: '/ml_2025_ii'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
